version: '3.8'

services:
  loadbalancer:
    build: .
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: info
    volumes:
      - ./configs:/app/configs
    depends_on:
      - backend1
      - backend2
    networks:
      - lb-network

  backend1:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lb-network

  backend2:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lb-network

networks:
  lb-network:
    driver: bridge