listenAddress: ":8080"
backends:
  - "http://backend1:80"
  - "http://backend2:80"

log:
  level: "info"
  format: "text"

healthCheck:
  enabled: true
  interval: "10s"
  timeout: "2s"
  path: "/health"

rateLimit:
  enabled: true
  middleware: true
  defaultCapacity: 100
  defaultRatePerSecond: 10

loadBalancer:
  strategy: "round-robin"  # или "least-connections", "random"